export { createClient, isTwoFactorChallenge, TwoFactorRequiredError } from './client';
export type {
  LibertinClient,
  LoginRequest,
  LoginResult,
  RegisterRequest,
  VerifyRequest,
  VerifyResponse,
  AuthResponse,
  User,
  UserRole,
  PublicUser,
  Profile,
  UpdateProfileRequest,
  FeedItem,
  FeedResponse,
  Conversation,
  MessagesResponse,
  ErrorCode,
  ErrorResponse,
  // 2FA — designed surface, ADR 0001 §9 (no backend yet, D-003)
  TwoFactorApi,
  TwoFactorMethod,
  TwoFactorMethodRef,
  TwoFactorChallenge,
  TwoFactorChallengeRequest,
  TwoFactorChallengeResult,
  SmsChallengeResult,
  PasskeyChallengeResult,
  TotpChallengeResult,
  TwoFactorVerifyRequest,
  TwoFactorAuthResponse,
  RecoveryCodeRequest,
  RecoveryCodeAuthResponse,
  PasskeyLoginRequest,
  TwoFactorFactor,
  TwoFactorFactorsResponse,
  TotpEnrollResponse,
  FactorActivateRequest,
  FactorActivateResponse,
  SmsEnrollRequest,
  SmsEnrollResponse,
  SmsActivateResponse,
  PasskeyRegisterRequest,
  PasskeyRegisterResponse,
  RecoveryCodesResponse,
  RecoveryCodesStatus,
  RecoveryRequest,
  RecoveryStatus,
  RecoveryCancelRequest,
  Session,
  SessionsResponse,
  PublicKeyCredentialDescriptorJSON,
  PublicKeyCredentialRequestOptionsJSON,
  PublicKeyCredentialCreationOptionsJSON,
  AuthenticatorAssertionJSON,
  AuthenticatorAttestationJSON,
} from './client';
export { handlers } from './mocks/handlers';
export { worker } from './mocks/browser';
export { server } from './mocks/server';
