#!/bin/bash
# Test LEDs on different pins to find correct connection

echo "=== LED Pin Diagnostic ==="
echo "This will help identify which pin your LEDs are connected to"
echo ""
echo "Current firmware uses pin 6"
echo ""
echo "If LEDs don't work on pin 6, try these common pins:"
echo "  - Pin 3 (PWM)"
echo "  - Pin 5 (PWM)"
echo "  - Pin 9 (PWM)"
echo "  - Pin 10 (PWM)"
echo "  - Pin 11 (PWM)"
echo ""
echo "To test a different pin:"
echo "  1. Edit ai-servis/arduino/led_strip_controller/pin_test.ino"
echo "  2. Change: #define TEST_PIN 6  to your pin number"
echo "  3. Upload: cd ai-servis/arduino/led_strip_controller && arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:uno ."
echo "  4. Watch for LEDs lighting up"
echo ""
echo "Hardware checklist:"
echo "  [ ] LED data wire connected to Arduino pin"
echo "  [ ] LED power (5V) connected to external supply (2A+ recommended)"
echo "  [ ] LED ground connected to Arduino ground"
echo "  [ ] Power supply provides sufficient current (1.4A+ minimum)"
echo "  [ ] All connections are secure"
