find_library(TEST_LIB NAMES jsoncpp PATHS /home/mia/.conan2/p/b/jsonc9d47ec8a0da15/p/lib NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
message("TEST_LIB: ${TEST_LIB}")
message("CMAKE_FIND_LIBRARY_PREFIXES: ${CMAKE_FIND_LIBRARY_PREFIXES}")
message("CMAKE_FIND_LIBRARY_SUFFIXES: ${CMAKE_FIND_LIBRARY_SUFFIXES}")