# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

class AIState(object):
    Listening = 0
    Speaking = 1
    Thinking = 2
    Recording = 3
    Error = 4
    Idle = 5
