# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioFeatures(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 20

    # AudioFeatures
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioFeatures
    def Bpm(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # AudioFeatures
    def BeatConfidence(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # AudioFeatures
    def DominantFreq(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # AudioFeatures
    def RmsEnergy(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # AudioFeatures
    def TimestampMs(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateAudioFeatures(builder, bpm, beatConfidence, dominantFreq, rmsEnergy, timestampMs):
    builder.Prep(4, 20)
    builder.PrependUint32(timestampMs)
    builder.PrependFloat32(rmsEnergy)
    builder.PrependFloat32(dominantFreq)
    builder.PrependFloat32(beatConfidence)
    builder.PrependFloat32(bpm)
    return builder.Offset()
