# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BeatEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # BeatEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BeatEvent
    def Bpm(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BeatEvent
    def BeatConfidence(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # BeatEvent
    def BeatNumber(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # BeatEvent
    def TimestampMs(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateBeatEvent(builder, bpm, beatConfidence, beatNumber, timestampMs):
    builder.Prep(4, 16)
    builder.PrependUint32(timestampMs)
    builder.PrependUint32(beatNumber)
    builder.PrependFloat32(beatConfidence)
    builder.PrependFloat32(bpm)
    return builder.Offset()
