# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CommandAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CommandAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandAck
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandAck
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CommandAck
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandAck
    def ResponseData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CommandAck
    def ResponseDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CommandAck
    def ResponseDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CommandAck
    def ResponseDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # CommandAck
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CommandAckStart(builder):
    builder.StartObject(5)

def Start(builder):
    CommandAckStart(builder)

def CommandAckAddCommandId(builder, commandId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(commandId), 0)

def AddCommandId(builder, commandId):
    CommandAckAddCommandId(builder, commandId)

def CommandAckAddStatus(builder, status):
    builder.PrependInt8Slot(1, status, 0)

def AddStatus(builder, status):
    CommandAckAddStatus(builder, status)

def CommandAckAddErrorMessage(builder, errorMessage):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)

def AddErrorMessage(builder, errorMessage):
    CommandAckAddErrorMessage(builder, errorMessage)

def CommandAckAddResponseData(builder, responseData):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(responseData), 0)

def AddResponseData(builder, responseData):
    CommandAckAddResponseData(builder, responseData)

def CommandAckStartResponseDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartResponseDataVector(builder, numElems):
    return CommandAckStartResponseDataVector(builder, numElems)

def CommandAckAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(4, timestamp, 0)

def AddTimestamp(builder, timestamp):
    CommandAckAddTimestamp(builder, timestamp)

def CommandAckEnd(builder):
    return builder.EndObject()

def End(builder):
    return CommandAckEnd(builder)
