# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DeviceInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDeviceInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DeviceInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceInfo
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceInfo
    def DeviceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # DeviceInfo
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceInfo
    def Capabilities(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # DeviceInfo
    def CapabilitiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DeviceInfo
    def CapabilitiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # DeviceInfo
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceInfo
    def LastSeen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DeviceInfo
    def Metadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DeviceInfo
    def MetadataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DeviceInfo
    def MetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DeviceInfo
    def MetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def DeviceInfoStart(builder):
    builder.StartObject(7)

def Start(builder):
    DeviceInfoStart(builder)

def DeviceInfoAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    DeviceInfoAddDeviceId(builder, deviceId)

def DeviceInfoAddDeviceType(builder, deviceType):
    builder.PrependInt8Slot(1, deviceType, 0)

def AddDeviceType(builder, deviceType):
    DeviceInfoAddDeviceType(builder, deviceType)

def DeviceInfoAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    DeviceInfoAddName(builder, name)

def DeviceInfoAddCapabilities(builder, capabilities):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(capabilities), 0)

def AddCapabilities(builder, capabilities):
    DeviceInfoAddCapabilities(builder, capabilities)

def DeviceInfoStartCapabilitiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCapabilitiesVector(builder, numElems):
    return DeviceInfoStartCapabilitiesVector(builder, numElems)

def DeviceInfoAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    DeviceInfoAddStatus(builder, status)

def DeviceInfoAddLastSeen(builder, lastSeen):
    builder.PrependUint64Slot(5, lastSeen, 0)

def AddLastSeen(builder, lastSeen):
    DeviceInfoAddLastSeen(builder, lastSeen)

def DeviceInfoAddMetadata(builder, metadata):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)

def AddMetadata(builder, metadata):
    DeviceInfoAddMetadata(builder, metadata)

def DeviceInfoStartMetadataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartMetadataVector(builder, numElems):
    return DeviceInfoStartMetadataVector(builder, numElems)

def DeviceInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return DeviceInfoEnd(builder)
