# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GPIOCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GPIOCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGPIOCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GPIOCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GPIOCommand
    def Pin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GPIOCommand
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # GPIOCommand
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GPIOCommand
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def GPIOCommandStart(builder):
    builder.StartObject(4)

def Start(builder):
    GPIOCommandStart(builder)

def GPIOCommandAddPin(builder, pin):
    builder.PrependInt32Slot(0, pin, 0)

def AddPin(builder, pin):
    GPIOCommandAddPin(builder, pin)

def GPIOCommandAddDirection(builder, direction):
    builder.PrependInt8Slot(1, direction, 0)

def AddDirection(builder, direction):
    GPIOCommandAddDirection(builder, direction)

def GPIOCommandAddValue(builder, value):
    builder.PrependBoolSlot(2, value, 0)

def AddValue(builder, value):
    GPIOCommandAddValue(builder, value)

def GPIOCommandAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(3, timestamp, 0)

def AddTimestamp(builder, timestamp):
    GPIOCommandAddTimestamp(builder, timestamp)

def GPIOCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return GPIOCommandEnd(builder)
