# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GPIOResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GPIOResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGPIOResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GPIOResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GPIOResponse
    def Pin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GPIOResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GPIOResponse
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GPIOResponse
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GPIOResponse
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def GPIOResponseStart(builder):
    builder.StartObject(5)

def Start(builder):
    GPIOResponseStart(builder)

def GPIOResponseAddPin(builder, pin):
    builder.PrependInt32Slot(0, pin, 0)

def AddPin(builder, pin):
    GPIOResponseAddPin(builder, pin)

def GPIOResponseAddSuccess(builder, success):
    builder.PrependBoolSlot(1, success, 0)

def AddSuccess(builder, success):
    GPIOResponseAddSuccess(builder, success)

def GPIOResponseAddValue(builder, value):
    builder.PrependBoolSlot(2, value, 0)

def AddValue(builder, value):
    GPIOResponseAddValue(builder, value)

def GPIOResponseAddErrorMessage(builder, errorMessage):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)

def AddErrorMessage(builder, errorMessage):
    GPIOResponseAddErrorMessage(builder, errorMessage)

def GPIOResponseAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(4, timestamp, 0)

def AddTimestamp(builder, timestamp):
    GPIOResponseAddTimestamp(builder, timestamp)

def GPIOResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return GPIOResponseEnd(builder)
