# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LEDState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LEDState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLEDState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LEDState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LEDState
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # LEDState
    def AiState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # LEDState
    def Brightness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LEDState
    def ServiceStatus(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # LEDState
    def ServiceStatusLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LEDState
    def ServiceStatusIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # LEDState
    def ObdData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # LEDState
    def ObdDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # LEDState
    def ObdDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LEDState
    def ObdDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # LEDState
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def LEDStateStart(builder):
    builder.StartObject(6)

def Start(builder):
    LEDStateStart(builder)

def LEDStateAddMode(builder, mode):
    builder.PrependInt8Slot(0, mode, 0)

def AddMode(builder, mode):
    LEDStateAddMode(builder, mode)

def LEDStateAddAiState(builder, aiState):
    builder.PrependInt8Slot(1, aiState, 0)

def AddAiState(builder, aiState):
    LEDStateAddAiState(builder, aiState)

def LEDStateAddBrightness(builder, brightness):
    builder.PrependFloat32Slot(2, brightness, 0.0)

def AddBrightness(builder, brightness):
    LEDStateAddBrightness(builder, brightness)

def LEDStateAddServiceStatus(builder, serviceStatus):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(serviceStatus), 0)

def AddServiceStatus(builder, serviceStatus):
    LEDStateAddServiceStatus(builder, serviceStatus)

def LEDStateStartServiceStatusVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartServiceStatusVector(builder, numElems):
    return LEDStateStartServiceStatusVector(builder, numElems)

def LEDStateAddObdData(builder, obdData):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(obdData), 0)

def AddObdData(builder, obdData):
    LEDStateAddObdData(builder, obdData)

def LEDStateStartObdDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartObdDataVector(builder, numElems):
    return LEDStateStartObdDataVector(builder, numElems)

def LEDStateAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(5, timestamp, 0)

def AddTimestamp(builder, timestamp):
    LEDStateAddTimestamp(builder, timestamp)

def LEDStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return LEDStateEnd(builder)
