# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

class SensorType(object):
    Temperature = 0
    Humidity = 1
    Distance = 2
    Pressure = 3
    Light = 4
    Motion = 5
