# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SensorTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SensorTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorTelemetry
    def SensorId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SensorTelemetry
    def SensorType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SensorTelemetry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SensorTelemetry
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SensorTelemetry
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SensorTelemetry
    def Metadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SensorTelemetry
    def MetadataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SensorTelemetry
    def MetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorTelemetry
    def MetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def SensorTelemetryStart(builder):
    builder.StartObject(6)

def Start(builder):
    SensorTelemetryStart(builder)

def SensorTelemetryAddSensorId(builder, sensorId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sensorId), 0)

def AddSensorId(builder, sensorId):
    SensorTelemetryAddSensorId(builder, sensorId)

def SensorTelemetryAddSensorType(builder, sensorType):
    builder.PrependInt8Slot(1, sensorType, 0)

def AddSensorType(builder, sensorType):
    SensorTelemetryAddSensorType(builder, sensorType)

def SensorTelemetryAddValue(builder, value):
    builder.PrependFloat32Slot(2, value, 0.0)

def AddValue(builder, value):
    SensorTelemetryAddValue(builder, value)

def SensorTelemetryAddUnit(builder, unit):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0)

def AddUnit(builder, unit):
    SensorTelemetryAddUnit(builder, unit)

def SensorTelemetryAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(4, timestamp, 0)

def AddTimestamp(builder, timestamp):
    SensorTelemetryAddTimestamp(builder, timestamp)

def SensorTelemetryAddMetadata(builder, metadata):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)

def AddMetadata(builder, metadata):
    SensorTelemetryAddMetadata(builder, metadata)

def SensorTelemetryStartMetadataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartMetadataVector(builder, numElems):
    return SensorTelemetryStartMetadataVector(builder, numElems)

def SensorTelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return SensorTelemetryEnd(builder)
