# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSystemStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SystemStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemStatus
    def UptimeSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SystemStatus
    def MemoryPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SystemStatus
    def CpuPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SystemStatus
    def DeviceCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SystemStatus
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def SystemStatusStart(builder):
    builder.StartObject(5)

def Start(builder):
    SystemStatusStart(builder)

def SystemStatusAddUptimeSeconds(builder, uptimeSeconds):
    builder.PrependUint64Slot(0, uptimeSeconds, 0)

def AddUptimeSeconds(builder, uptimeSeconds):
    SystemStatusAddUptimeSeconds(builder, uptimeSeconds)

def SystemStatusAddMemoryPercent(builder, memoryPercent):
    builder.PrependFloat32Slot(1, memoryPercent, 0.0)

def AddMemoryPercent(builder, memoryPercent):
    SystemStatusAddMemoryPercent(builder, memoryPercent)

def SystemStatusAddCpuPercent(builder, cpuPercent):
    builder.PrependFloat32Slot(2, cpuPercent, 0.0)

def AddCpuPercent(builder, cpuPercent):
    SystemStatusAddCpuPercent(builder, cpuPercent)

def SystemStatusAddDeviceCount(builder, deviceCount):
    builder.PrependInt32Slot(3, deviceCount, 0)

def AddDeviceCount(builder, deviceCount):
    SystemStatusAddDeviceCount(builder, deviceCount)

def SystemStatusAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(4, timestamp, 0)

def AddTimestamp(builder, timestamp):
    SystemStatusAddTimestamp(builder, timestamp)

def SystemStatusEnd(builder):
    return builder.EndObject()

def End(builder):
    return SystemStatusEnd(builder)
