# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Mia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicleTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VehicleTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleTelemetry
    def Rpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def SpeedKmh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def CoolantTempC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def OilTemperatureC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def BatteryVoltage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def DpfSootLoadPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def DpfSootMassG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def DpfRegenerationStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # VehicleTelemetry
    def EolysAdditiveLevelPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def EolysAdditiveLevelL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def IntakeAirTempC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def FuelLevelPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def EngineLoadPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VehicleTelemetry
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def VehicleTelemetryStart(builder):
    builder.StartObject(14)

def Start(builder):
    VehicleTelemetryStart(builder)

def VehicleTelemetryAddRpm(builder, rpm):
    builder.PrependFloat32Slot(0, rpm, 0.0)

def AddRpm(builder, rpm):
    VehicleTelemetryAddRpm(builder, rpm)

def VehicleTelemetryAddSpeedKmh(builder, speedKmh):
    builder.PrependFloat32Slot(1, speedKmh, 0.0)

def AddSpeedKmh(builder, speedKmh):
    VehicleTelemetryAddSpeedKmh(builder, speedKmh)

def VehicleTelemetryAddCoolantTempC(builder, coolantTempC):
    builder.PrependFloat32Slot(2, coolantTempC, 0.0)

def AddCoolantTempC(builder, coolantTempC):
    VehicleTelemetryAddCoolantTempC(builder, coolantTempC)

def VehicleTelemetryAddOilTemperatureC(builder, oilTemperatureC):
    builder.PrependFloat32Slot(3, oilTemperatureC, 0.0)

def AddOilTemperatureC(builder, oilTemperatureC):
    VehicleTelemetryAddOilTemperatureC(builder, oilTemperatureC)

def VehicleTelemetryAddBatteryVoltage(builder, batteryVoltage):
    builder.PrependFloat32Slot(4, batteryVoltage, 0.0)

def AddBatteryVoltage(builder, batteryVoltage):
    VehicleTelemetryAddBatteryVoltage(builder, batteryVoltage)

def VehicleTelemetryAddDpfSootLoadPercent(builder, dpfSootLoadPercent):
    builder.PrependFloat32Slot(5, dpfSootLoadPercent, 0.0)

def AddDpfSootLoadPercent(builder, dpfSootLoadPercent):
    VehicleTelemetryAddDpfSootLoadPercent(builder, dpfSootLoadPercent)

def VehicleTelemetryAddDpfSootMassG(builder, dpfSootMassG):
    builder.PrependFloat32Slot(6, dpfSootMassG, 0.0)

def AddDpfSootMassG(builder, dpfSootMassG):
    VehicleTelemetryAddDpfSootMassG(builder, dpfSootMassG)

def VehicleTelemetryAddDpfRegenerationStatus(builder, dpfRegenerationStatus):
    builder.PrependInt8Slot(7, dpfRegenerationStatus, 0)

def AddDpfRegenerationStatus(builder, dpfRegenerationStatus):
    VehicleTelemetryAddDpfRegenerationStatus(builder, dpfRegenerationStatus)

def VehicleTelemetryAddEolysAdditiveLevelPercent(builder, eolysAdditiveLevelPercent):
    builder.PrependFloat32Slot(8, eolysAdditiveLevelPercent, 0.0)

def AddEolysAdditiveLevelPercent(builder, eolysAdditiveLevelPercent):
    VehicleTelemetryAddEolysAdditiveLevelPercent(builder, eolysAdditiveLevelPercent)

def VehicleTelemetryAddEolysAdditiveLevelL(builder, eolysAdditiveLevelL):
    builder.PrependFloat32Slot(9, eolysAdditiveLevelL, 0.0)

def AddEolysAdditiveLevelL(builder, eolysAdditiveLevelL):
    VehicleTelemetryAddEolysAdditiveLevelL(builder, eolysAdditiveLevelL)

def VehicleTelemetryAddIntakeAirTempC(builder, intakeAirTempC):
    builder.PrependFloat32Slot(10, intakeAirTempC, 0.0)

def AddIntakeAirTempC(builder, intakeAirTempC):
    VehicleTelemetryAddIntakeAirTempC(builder, intakeAirTempC)

def VehicleTelemetryAddFuelLevelPercent(builder, fuelLevelPercent):
    builder.PrependFloat32Slot(11, fuelLevelPercent, 0.0)

def AddFuelLevelPercent(builder, fuelLevelPercent):
    VehicleTelemetryAddFuelLevelPercent(builder, fuelLevelPercent)

def VehicleTelemetryAddEngineLoadPercent(builder, engineLoadPercent):
    builder.PrependFloat32Slot(12, engineLoadPercent, 0.0)

def AddEngineLoadPercent(builder, engineLoadPercent):
    VehicleTelemetryAddEngineLoadPercent(builder, engineLoadPercent)

def VehicleTelemetryAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(13, timestamp, 0)

def AddTimestamp(builder, timestamp):
    VehicleTelemetryAddTimestamp(builder, timestamp)

def VehicleTelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleTelemetryEnd(builder)
