#!/bin/bash
#
# ensure-bundled-cpython.sh - Ensure bundled CPython is used for MIA execution
#
# This script ensures that MIA Python scripts use the bundled CPython executable
# instead of system Python. It should be run after MIA installation.
#
# Usage: ./ensure-bundled-cpython.sh [install_dir]
#

set -euo pipefail

# Default installation directory and writable override points for testing.
INSTALL_DIR="${1:-${MIA_INSTALL_DIR:-/opt/mia/rpi}}"
ENV_FILE="${MIA_ENV_FILE:-/etc/mia/environment}"
CONVENIENCE_SCRIPT="${MIA_PYTHON_WRAPPER:-/usr/local/bin/mia-python}"
SYSTEMD_DIR="${MIA_SYSTEMD_DIR:-/etc/systemd/system}"
USE_SUDO="${MIA_USE_SUDO:-auto}"

run_privileged() {
    if [[ "$USE_SUDO" == "0" || "$USE_SUDO" == "false" || "$USE_SUDO" == "no" ]]; then
        "$@"
    elif [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
        "$@"
    else
        sudo "$@"
    fi
}

find_python_bin() {
    local candidates=(
        "$INSTALL_DIR/bin/python3"
        "$INSTALL_DIR/bin/python"
    )
    local candidate

    for candidate in "${candidates[@]}"; do
        if [[ -x "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done

    shopt -s nullglob
    for candidate in "$INSTALL_DIR"/bin/python3.*; do
        if [[ -x "$candidate" ]]; then
            printf '%s\n' "$candidate"
            shopt -u nullglob
            return 0
        fi
    done
    shopt -u nullglob

    return 1
}

read_python_layout() {
    while IFS='=' read -r key value; do
        case "$key" in
            PYTHON_EXECUTABLE) PYTHON_EXECUTABLE="$value" ;;
            PYTHON_HOME) PYTHON_HOME="$value" ;;
            PYTHON_VERSION) PYTHON_VERSION="$value" ;;
            PYTHON_STDLIB) PYTHON_STDLIB="$value" ;;
            PYTHON_PURELIB) PYTHON_PURELIB="$value" ;;
            PYTHON_PLATLIB) PYTHON_PLATLIB="$value" ;;
            PYTHON_SITE_PACKAGES) PYTHON_SITE_PACKAGES="$value" ;;
        esac
    done < <("$CPYTHON_BIN" <<'PY'
import site
import sys
import sysconfig

paths = sysconfig.get_paths()
site_paths = []
getter = getattr(site, "getsitepackages", None)
if getter is not None:
    try:
        for path in getter():
            if path and path.startswith(sys.base_prefix) and path not in site_paths:
                site_paths.append(path)
    except Exception:
        pass

print(f"PYTHON_EXECUTABLE={sys.executable}")
print(f"PYTHON_HOME={sys.base_prefix}")
print(f"PYTHON_VERSION={sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
print(f"PYTHON_STDLIB={paths.get('stdlib', '')}")
print(f"PYTHON_PURELIB={paths.get('purelib', '')}")
print(f"PYTHON_PLATLIB={paths.get('platlib', '')}")
print(f"PYTHON_SITE_PACKAGES={':'.join(site_paths)}")
PY
)

    PYTHON_BIN_DIR="$(dirname "$PYTHON_EXECUTABLE")"
}

CPYTHON_BIN="$(find_python_bin || true)"

echo "🔍 Ensuring bundled CPython is available for MIA..."

# Check if bundled CPython exists
if [[ -z "$CPYTHON_BIN" || ! -x "$CPYTHON_BIN" ]]; then
    echo "❌ Bundled CPython not found at: $CPYTHON_BIN"
    echo "   Please ensure MIA is properly installed with sparetools-cpython dependency"
    exit 1
fi

echo "✅ Bundled CPython found at: $CPYTHON_BIN"

# Verify Python version and functionality
echo "📋 Verifying bundled Python functionality..."
if ! "$CPYTHON_BIN" --version >/dev/null 2>&1; then
    echo "❌ Bundled Python is not executable"
    exit 1
fi

if ! "$CPYTHON_BIN" -c "import sys; print(f'Python {sys.version}')"; then
    echo "❌ Bundled Python cannot import standard library"
    exit 1
fi

read_python_layout

echo "📦 Detected bundled Python home: $PYTHON_HOME"
echo "📦 Detected bundled Python version: $PYTHON_VERSION"

if [[ "$PYTHON_HOME" != "$INSTALL_DIR"* ]]; then
    echo "⚠️  Bundled Python reports base prefix '$PYTHON_HOME' instead of '$INSTALL_DIR'"
    echo "   Using detected Python home from the interpreter to avoid mismatched stdlib paths"
fi

echo "✅ Bundled Python is functional"

# Create environment file for systemd services
echo "📝 Creating environment configuration at: $ENV_FILE"

run_privileged mkdir -p "$(dirname "$ENV_FILE")"

run_privileged tee "$ENV_FILE" > /dev/null << EOF
# MIA Environment Configuration
# Ensures bundled CPython is used for all Python execution.
# Generated by scripts/ensure-bundled-cpython.sh

# Python Configuration
PYTHONHOME=$PYTHON_HOME
PATH=$PYTHON_BIN_DIR:/usr/local/bin:/usr/bin
PYTHONNOUSERSITE=1

# MIA Specific
MIA_INSTALL_DIR=$INSTALL_DIR
MIA_PYTHON=$CPYTHON_BIN
MIA_PYTHON_VERSION=$PYTHON_VERSION
MIA_PYTHON_STDLIB=$PYTHON_STDLIB
MIA_PYTHON_SITE_PACKAGES=$PYTHON_SITE_PACKAGES
EOF

echo "✅ Environment configuration created"

# Verify systemd services are configured correctly
echo "🔧 Verifying systemd service configurations..."

SERVICES=(
    "mia-api.service"
    "mia-gpio-worker.service"
    "mia-serial-bridge.service"
    "mia-obd-worker.service"
    "mia-ble-obd.service"
)

for service in "${SERVICES[@]}"; do
    service_file="$SYSTEMD_DIR/$service"
    if [[ -f "$service_file" ]]; then
        if ! grep -Fq -- "$CPYTHON_BIN" "$service_file"; then
            echo "⚠️  Service $service may not be using bundled Python"
            echo "   Please ensure ExecStart uses: $CPYTHON_BIN"
            echo "   Optionally add EnvironmentFile=$ENV_FILE for consistent Python env settings"
        else
            echo "✅ Service $service uses bundled Python"
        fi
    else
        echo "ℹ️  Service $service not installed yet"
    fi
done

# Create convenience script for manual execution
echo "📝 Creating convenience script at: $CONVENIENCE_SCRIPT"

run_privileged tee "$CONVENIENCE_SCRIPT" > /dev/null << EOF
#!/bin/bash
# MIA Python wrapper - ensures bundled CPython is used
export PYTHONHOME="$PYTHON_HOME"
export PATH="$PYTHON_BIN_DIR:/usr/local/bin:/usr/bin"
export PYTHONNOUSERSITE=1
exec "$CPYTHON_BIN" "\$@"
EOF

run_privileged chmod +x "$CONVENIENCE_SCRIPT"

echo "✅ Convenience script created"

# Test the setup
echo "🧪 Testing MIA Python execution..."
if env -i \
    PYTHONHOME="$PYTHON_HOME" \
    PATH="$PYTHON_BIN_DIR:/usr/local/bin:/usr/bin" \
    PYTHONNOUSERSITE=1 \
    "$CPYTHON_BIN" -c "import sys, sysconfig; print(f'MIA Python setup successful: {sys.executable} ({sys.version.split()[0]})'); print(sysconfig.get_paths()['stdlib'])"; then
    echo "✅ MIA Python setup verified"
else
    echo "❌ MIA Python setup failed"
    exit 1
fi

echo ""
echo "🎉 Bundled CPython setup complete!"
echo ""
echo "Usage:"
echo "  Direct execution: $CPYTHON_BIN script.py"
echo "  Convenience script: mia-python script.py"
echo "  Systemd services: Environment file prepared; verify ExecStart and EnvironmentFile"
echo ""
echo "Environment variables set in: $ENV_FILE"