"""
Roundtrip tests for FlatBuffers schemas in Mia/.

These are intentionally cheap insurance against schema drift: for every
non-trivial table, build a message, serialize it, parse it back, and assert
field equality. Enum constants are also pinned so silent reordering fails
loudly.

The schemas are generated by the FlatBuffers compiler; if anyone regenerates
them with a different field order, these tests will catch the break.
"""

import os
import sys

import flatbuffers
import pytest

# Make repo root importable so `from Mia import ...` works regardless of
# where pytest is invoked.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from Mia import (  # noqa: E402
    AIState,
    CommandAck,
    CommandStatus,
    DeviceInfo,
    DeviceType,
    GPIOCommand,
    GPIODirection,
    SensorTelemetry,
    SensorType,
    VehicleTelemetry,
)


# --------------------------------------------------------------------------- #
# Enum stability
# --------------------------------------------------------------------------- #

class TestEnumStability:
    """Pin ordinal values so generated enums cannot silently reorder."""

    def test_ai_state_ordinals(self):
        assert AIState.AIState.Listening == 0
        assert AIState.AIState.Speaking == 1
        assert AIState.AIState.Thinking == 2
        assert AIState.AIState.Recording == 3
        assert AIState.AIState.Error == 4
        assert AIState.AIState.Idle == 5

    def test_device_type_ordinals(self):
        assert DeviceType.DeviceType.GPIO == 0
        assert DeviceType.DeviceType.Sensor == 1
        assert DeviceType.DeviceType.Actuator == 2
        assert DeviceType.DeviceType.Display == 3
        assert DeviceType.DeviceType.Network == 4

    def test_command_status_ordinals(self):
        assert CommandStatus.CommandStatus.Success == 0
        assert CommandStatus.CommandStatus.Failure == 1
        assert CommandStatus.CommandStatus.Timeout == 2
        assert CommandStatus.CommandStatus.Invalid == 3

    def test_sensor_type_ordinals(self):
        assert SensorType.SensorType.Temperature == 0
        assert SensorType.SensorType.Humidity == 1
        assert SensorType.SensorType.Distance == 2
        assert SensorType.SensorType.Pressure == 3
        assert SensorType.SensorType.Light == 4
        assert SensorType.SensorType.Motion == 5


# --------------------------------------------------------------------------- #
# GPIOCommand — all scalar fields
# --------------------------------------------------------------------------- #

class TestGPIOCommandRoundtrip:
    def test_roundtrip_all_fields(self):
        builder = flatbuffers.Builder(128)
        GPIOCommand.Start(builder)
        GPIOCommand.AddPin(builder, 17)
        GPIOCommand.AddDirection(builder, GPIODirection.GPIODirection.Output)
        GPIOCommand.AddValue(builder, True)
        GPIOCommand.AddTimestamp(builder, 1_700_000_000_000)
        end = GPIOCommand.End(builder)
        builder.Finish(end)

        parsed = GPIOCommand.GPIOCommand.GetRootAs(builder.Output(), 0)
        assert parsed.Pin() == 17
        assert parsed.Direction() == GPIODirection.GPIODirection.Output
        assert parsed.Value() is True
        assert parsed.Timestamp() == 1_700_000_000_000

    def test_defaults_when_unset(self):
        builder = flatbuffers.Builder(128)
        GPIOCommand.Start(builder)
        end = GPIOCommand.End(builder)
        builder.Finish(end)

        parsed = GPIOCommand.GPIOCommand.GetRootAs(builder.Output(), 0)
        assert parsed.Pin() == 0
        assert parsed.Value() is False
        assert parsed.Timestamp() == 0


# --------------------------------------------------------------------------- #
# SensorTelemetry — strings + floats + uint64
# --------------------------------------------------------------------------- #

class TestSensorTelemetryRoundtrip:
    def test_roundtrip_all_fields(self):
        builder = flatbuffers.Builder(256)
        sensor_id = builder.CreateString("temp-01")
        unit = builder.CreateString("celsius")

        SensorTelemetry.Start(builder)
        SensorTelemetry.AddSensorId(builder, sensor_id)
        SensorTelemetry.AddSensorType(builder, SensorType.SensorType.Temperature)
        SensorTelemetry.AddValue(builder, 21.5)
        SensorTelemetry.AddUnit(builder, unit)
        SensorTelemetry.AddTimestamp(builder, 1_234_567_890)
        end = SensorTelemetry.End(builder)
        builder.Finish(end)

        parsed = SensorTelemetry.SensorTelemetry.GetRootAs(builder.Output(), 0)
        assert parsed.SensorId() == b"temp-01"
        assert parsed.SensorType() == SensorType.SensorType.Temperature
        assert parsed.Value() == pytest.approx(21.5)
        assert parsed.Unit() == b"celsius"
        assert parsed.Timestamp() == 1_234_567_890


# --------------------------------------------------------------------------- #
# CommandAck — strings + enum + byte vector
# --------------------------------------------------------------------------- #

class TestCommandAckRoundtrip:
    def test_roundtrip_without_vector(self):
        builder = flatbuffers.Builder(128)
        cmd_id = builder.CreateString("cmd-abc")
        err = builder.CreateString("")

        CommandAck.Start(builder)
        CommandAck.AddCommandId(builder, cmd_id)
        CommandAck.AddStatus(builder, CommandStatus.CommandStatus.Success)
        CommandAck.AddErrorMessage(builder, err)
        CommandAck.AddTimestamp(builder, 42)
        end = CommandAck.End(builder)
        builder.Finish(end)

        parsed = CommandAck.CommandAck.GetRootAs(builder.Output(), 0)
        assert parsed.CommandId() == b"cmd-abc"
        assert parsed.Status() == CommandStatus.CommandStatus.Success
        assert parsed.ErrorMessage() == b""
        assert parsed.Timestamp() == 42

    def test_roundtrip_with_response_data(self):
        builder = flatbuffers.Builder(128)

        # Build the byte vector first (flatbuffers requires reverse order of nesting).
        payload = bytes([1, 2, 3, 4, 5])
        CommandAck.StartResponseDataVector(builder, len(payload))
        for b in reversed(payload):
            builder.PrependByte(b)
        response_vec = builder.EndVector()

        cmd_id = builder.CreateString("cmd-xyz")
        err = builder.CreateString("oops")

        CommandAck.Start(builder)
        CommandAck.AddCommandId(builder, cmd_id)
        CommandAck.AddStatus(builder, CommandStatus.CommandStatus.Failure)
        CommandAck.AddErrorMessage(builder, err)
        CommandAck.AddResponseData(builder, response_vec)
        CommandAck.AddTimestamp(builder, 100)
        end = CommandAck.End(builder)
        builder.Finish(end)

        parsed = CommandAck.CommandAck.GetRootAs(builder.Output(), 0)
        assert parsed.CommandId() == b"cmd-xyz"
        assert parsed.Status() == CommandStatus.CommandStatus.Failure
        assert parsed.ErrorMessage() == b"oops"
        assert parsed.ResponseDataLength() == 5
        assert [parsed.ResponseData(i) for i in range(5)] == list(payload)
        assert parsed.Timestamp() == 100


# --------------------------------------------------------------------------- #
# DeviceInfo — string vector of capabilities
# --------------------------------------------------------------------------- #

class TestDeviceInfoRoundtrip:
    def test_roundtrip_with_capabilities(self):
        builder = flatbuffers.Builder(256)

        cap_1 = builder.CreateString("read")
        cap_2 = builder.CreateString("write")
        DeviceInfo.StartCapabilitiesVector(builder, 2)
        builder.PrependUOffsetTRelative(cap_2)
        builder.PrependUOffsetTRelative(cap_1)
        caps_vec = builder.EndVector()

        device_id = builder.CreateString("gpio-17")
        name = builder.CreateString("Kitchen Light")
        status = builder.CreateString("online")

        DeviceInfo.Start(builder)
        DeviceInfo.AddDeviceId(builder, device_id)
        DeviceInfo.AddDeviceType(builder, DeviceType.DeviceType.GPIO)
        DeviceInfo.AddName(builder, name)
        DeviceInfo.AddCapabilities(builder, caps_vec)
        DeviceInfo.AddStatus(builder, status)
        DeviceInfo.AddLastSeen(builder, 999)
        end = DeviceInfo.End(builder)
        builder.Finish(end)

        parsed = DeviceInfo.DeviceInfo.GetRootAs(builder.Output(), 0)
        assert parsed.DeviceId() == b"gpio-17"
        assert parsed.DeviceType() == DeviceType.DeviceType.GPIO
        assert parsed.Name() == b"Kitchen Light"
        assert parsed.Status() == b"online"
        assert parsed.LastSeen() == 999
        assert parsed.CapabilitiesLength() == 2
        assert parsed.Capabilities(0) == b"read"
        assert parsed.Capabilities(1) == b"write"


# --------------------------------------------------------------------------- #
# VehicleTelemetry — many float fields
# --------------------------------------------------------------------------- #

class TestVehicleTelemetryRoundtrip:
    def test_roundtrip_key_fields(self):
        builder = flatbuffers.Builder(256)
        VehicleTelemetry.Start(builder)
        VehicleTelemetry.AddDpfSootMassG(builder, 12.5)
        VehicleTelemetry.AddEolysAdditiveLevelPercent(builder, 70.0)
        VehicleTelemetry.AddEolysAdditiveLevelL(builder, 0.75)
        VehicleTelemetry.AddIntakeAirTempC(builder, 22.3)
        VehicleTelemetry.AddFuelLevelPercent(builder, 42.0)
        VehicleTelemetry.AddEngineLoadPercent(builder, 55.5)
        VehicleTelemetry.AddTimestamp(builder, 1_700_000_000)
        end = VehicleTelemetry.End(builder)
        builder.Finish(end)

        parsed = VehicleTelemetry.VehicleTelemetry.GetRootAs(builder.Output(), 0)
        assert parsed.DpfSootMassG() == pytest.approx(12.5)
        assert parsed.EolysAdditiveLevelPercent() == pytest.approx(70.0)
        assert parsed.EolysAdditiveLevelL() == pytest.approx(0.75)
        assert parsed.IntakeAirTempC() == pytest.approx(22.3)
        assert parsed.FuelLevelPercent() == pytest.approx(42.0)
        assert parsed.EngineLoadPercent() == pytest.approx(55.5)
        assert parsed.Timestamp() == 1_700_000_000

    def test_defaults_when_unset(self):
        builder = flatbuffers.Builder(64)
        VehicleTelemetry.Start(builder)
        end = VehicleTelemetry.End(builder)
        builder.Finish(end)

        parsed = VehicleTelemetry.VehicleTelemetry.GetRootAs(builder.Output(), 0)
        assert parsed.DpfSootMassG() == pytest.approx(0.0)
        assert parsed.FuelLevelPercent() == pytest.approx(0.0)
        assert parsed.Timestamp() == 0
