# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Vehicle

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CitroenTelemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CitroenTelemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCitroenTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CitroenTelemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CitroenTelemetry
    def Rpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def SpeedKmh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def CoolantTempC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def DpfSootLoadPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def DpfSootMassG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def DpfRegenerationStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CitroenTelemetry
    def EolysAdditiveLevelPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def EolysAdditiveLevelL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def BatteryVoltage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CitroenTelemetry
    def OilTemperatureC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def CitroenTelemetryStart(builder): builder.StartObject(10)
def Start(builder):
    return CitroenTelemetryStart(builder)
def CitroenTelemetryAddRpm(builder, rpm): builder.PrependFloat32Slot(0, rpm, 0.0)
def AddRpm(builder, rpm):
    return CitroenTelemetryAddRpm(builder, rpm)
def CitroenTelemetryAddSpeedKmh(builder, speedKmh): builder.PrependFloat32Slot(1, speedKmh, 0.0)
def AddSpeedKmh(builder, speedKmh):
    return CitroenTelemetryAddSpeedKmh(builder, speedKmh)
def CitroenTelemetryAddCoolantTempC(builder, coolantTempC): builder.PrependFloat32Slot(2, coolantTempC, 0.0)
def AddCoolantTempC(builder, coolantTempC):
    return CitroenTelemetryAddCoolantTempC(builder, coolantTempC)
def CitroenTelemetryAddDpfSootLoadPercent(builder, dpfSootLoadPercent): builder.PrependFloat32Slot(3, dpfSootLoadPercent, 0.0)
def AddDpfSootLoadPercent(builder, dpfSootLoadPercent):
    return CitroenTelemetryAddDpfSootLoadPercent(builder, dpfSootLoadPercent)
def CitroenTelemetryAddDpfSootMassG(builder, dpfSootMassG): builder.PrependFloat32Slot(4, dpfSootMassG, 0.0)
def AddDpfSootMassG(builder, dpfSootMassG):
    return CitroenTelemetryAddDpfSootMassG(builder, dpfSootMassG)
def CitroenTelemetryAddDpfRegenerationStatus(builder, dpfRegenerationStatus): builder.PrependInt8Slot(5, dpfRegenerationStatus, 0)
def AddDpfRegenerationStatus(builder, dpfRegenerationStatus):
    return CitroenTelemetryAddDpfRegenerationStatus(builder, dpfRegenerationStatus)
def CitroenTelemetryAddEolysAdditiveLevelPercent(builder, eolysAdditiveLevelPercent): builder.PrependFloat32Slot(6, eolysAdditiveLevelPercent, 0.0)
def AddEolysAdditiveLevelPercent(builder, eolysAdditiveLevelPercent):
    return CitroenTelemetryAddEolysAdditiveLevelPercent(builder, eolysAdditiveLevelPercent)
def CitroenTelemetryAddEolysAdditiveLevelL(builder, eolysAdditiveLevelL): builder.PrependFloat32Slot(7, eolysAdditiveLevelL, 0.0)
def AddEolysAdditiveLevelL(builder, eolysAdditiveLevelL):
    return CitroenTelemetryAddEolysAdditiveLevelL(builder, eolysAdditiveLevelL)
def CitroenTelemetryAddBatteryVoltage(builder, batteryVoltage): builder.PrependFloat32Slot(8, batteryVoltage, 0.0)
def AddBatteryVoltage(builder, batteryVoltage):
    return CitroenTelemetryAddBatteryVoltage(builder, batteryVoltage)
def CitroenTelemetryAddOilTemperatureC(builder, oilTemperatureC): builder.PrependFloat32Slot(9, oilTemperatureC, 0.0)
def AddOilTemperatureC(builder, oilTemperatureC):
    return CitroenTelemetryAddOilTemperatureC(builder, oilTemperatureC)
def CitroenTelemetryEnd(builder): return builder.EndObject()
def End(builder):
    return CitroenTelemetryEnd(builder)